// Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

// Mod
archives_base_name=MineColonies_Compatibility
maven_group=steve_gall.minecolonies_compatibility
mod_id=minecolonies_compatibility
mod_version=3.53
mod_name=Compatibility addon for MineColonies
mod_description=
mod_license=GPL 3.0
mod_homepage=https://legacy.curseforge.com/minecraft/mc-mods/minecolonies-compatibility
mod_source=https://github.com/gisellevonbingen-Minecraft/MineColonies_Compatibility
mod_issues=https://github.com/gisellevonbingen-Minecraft/MineColonies_Compatibility/issues

// Minecraft, Mod Loader
mc_version=1.21.1
neoforge_loader_version=4
neoforge_api_version=21.1.228
neoforge_api_version_range=[21.1.194,)

// Required
minecolonies_version=1.1.1368-1.21.1-snapshot
structurize_version=1.0.832-1.21.1-snapshot
multipiston_version=1.2.51-1.21.1-snapshot
blockui_version=1.0.199-1.21.1-snapshot
domumornamentum_version=1.0.223-snapshot
domumornamentum_file=7231908
minecolonies_tweaks_version=3.33

// Optional
jei_version=19.19.6.235
architectury_api_file=5786327
kotlin_for_forge_version=5.9.0
geckolib_file=7707149
curios_file=6529130
polymorph_file=6794589
immersive_engineering_version=12.4.2-194
dualcodecs_version=0.1.2
croptopia_file=6788725
epherolib_file=5872111
pamhc2trees_file=6772154
farmers_delight_file=7801529
ars_nouveau_file=6954892
regions_unexplored_file=8226385
terrablender_file=6054947
cobblemon_file=6125026
aether_file=6894706
accessories_file=6942854
owolib_file=6785734
lets_do_vinery_file=7539914
lets_do_meadow_file=7051885
the_undergarden_file=6687578
oreberries_file=6123417
reliquary_file=6924075
refined_storage_file=7039043
appliedenergistics2_version=19.2.16
ewewukeks_musket_file=5805570
cloth_config_file=5729127
butchercraft_file=6714774
blueprint_file=6965808
atmospheric_file=6969589
neapolitan_file=6969600
tacz_file=7695875
jade_file=5729884
fruitsdelgiht_file=7041466
culturaldelights_file=6659969
create_version=6.0.8-169
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
ponder_version=1.0.69
dynamictrees_file=7661136
biolith_file=7074761
lithostitched_file=8378498
silentlib_file=6565251
silentgear_file=7870014
framework_file=7530361
scguns_file=8086478

// Runtime Only
mekanism_version=10.7.15.81
configured_file=5873783
